import { DM_Sans } from 'next/font/google';
import "./globals.css";
import Header from './layout/header/header';

const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}