import { DM_Sans, Roboto_Condensed } from 'next/font/google';
import "./globals.css";
import dynamic from 'next/dynamic';
import Initializer from '@/utils/initializer/initalizer';
const Footer = dynamic(() => import('@/layout/footer/footer'));
const Header = dynamic(() => import('@/layout/header/header'));

const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '500', '600', '700'],
});

const roboto = Roboto_Condensed({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.className}>
      <Initializer />

      <body>
        <Header roboto={roboto} />
        {children}
        <Footer />
      </body>
    </html>
  );
}